# A generative model


# Lesson 1 - Load data and get acquainted with the corpus


Step by step:

- Choose and download considerably amount of data from Gutenberg.org
- Look into the data, review some of the text
- Observe things (e.g. strange names), which must be considered when preparing the data


The first thing we did was to download Hans Christian Andersen fairytales from Gutenberg and look into some of the texts.

What do we need to look out for when cleaning the data:

- Punctuation 
- The file consist of multiple stories --> need to divide it into different parts (might be possible to split after headers written in capital letters) --> we will do this in lesson 5
- Capital letters as headers, might want to delete these
- Change everything to lower caser 
- Illustrations, delete them, written as ([Illustration: _His limbs were numbed, his beautiful eyes were closing.-])


In [1]:
#import packages
import re
import string
from numpy import array
from pickle import dump
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
from keras.models import load_model
from pickle import load
from random import randint
from keras.preprocessing.sequence import pad_sequences
import nltk.data
from nltk.tokenize import sent_tokenize, word_tokenize

from keras.preprocessing.sequence import pad_sequences

from keras.layers import Masking
import os


Using TensorFlow backend.


Documentation on the following coding block:
https://www.pythonforbeginners.com/files/reading-and-writing-files-in-python
- How to open text

In [2]:
#define a function to load the text into memory
def load_text(filename): #we decide that the function is called load_text
    file = open(filename, 'r') #open() is used to open/loading a filename 
    #the mode indicates how it should be opened, r = read, w = writing, a = appending 
    text = file.read() # read the file and assign it to the variable text
    file.close() #close the file again
    return text #ends function and specify what output the want, we want text

We have saved all the text files in a local folder on the computer. We need to first load these and then combine them into a single file. 

In [3]:
#define a path, the folder where the text files are placed
path = "/Users/signeklovekjaer/Documents/CognitiveScience/3.semester/Learning_with_digital_media/Exam_project/Jupiter_notebook/Data/"

#make a list that contains all the names of the files in the directory and assign it to a variable
filenames = os.listdir( path )

# print all the files in the directory 

#for file in filenames:
   #print(file)

In [4]:
#use .remove() to remove filenames 

filenames.remove('.DS_Store');

filenames.remove('fairytales.txt');

filenames.remove('clean_text_sentences.txt');



The variable called filenames, now contains all the text files in the folder 'Data'. We ran the model on a different computer than mine, as the processing power isn't strong enough to handle so much data. But to show how the code works, I will just overwrite the variable filenames with just two textfile names.   

In [5]:
#filenames with less data
filenames = ['32571-0.txt','2435-0.txt']
print(filenames)

['32571-0.txt', '2435-0.txt']


In [6]:
#change working directory to where the text files are placed
os.chdir('/Users/signeklovekjaer/Documents/CognitiveScience/3.semester/Learning_with_digital_media/Exam_project/Jupiter_notebook/Data/')

#combine all the text files into a single file called "fairytales.text"
with open('fairytales.txt', 'w') as outfile: #specify where the file should be saved and what it should be called (if a file with that name already exists, it will be overwritten, 'w' is used to edit and write new information to a file 
    for text in filenames: #for all the text in the filenames, do the following...
        with open(text) as infile:
            outfile.write(infile.read())

In [7]:
# load document
in_filename = 'fairytales.txt'
doc = load_text(in_filename)
print(doc[0:300])

THE FIR TREE


FAR away in the forest, where the warm sun and the fresh air made a
sweet resting place, grew a pretty little fir tree. The situation was
all that could be desired; and yet the tree was not happy, it wished so
much to be like its tall companions, the pines and firs which grew
around 


# Lesson 2 - Prepare the training data

Step by step:
- Clean the text e.g. normalize words to lowercase and delete punctuation from words, to reduce vocabulary size
- Organize the words into sequences and save these to a file


In [8]:
#removing illustration descriptions
doc = re.sub(r'\[[^)]*\]', '', doc) #using re.sub function and regular expressions 
#[ - an opening bracket 
#[^()]* - zero or more characters other than those defined, that is, any characters other than [ and ]
#\] - a closing bracket



In [9]:
#remove headers
doc = re.sub(r'[A-Z]{2,}', '', doc) #remove capital letters everytime there is more than two 

print(doc[0:300]) #lets look at it 


  


 away in the forest, where the warm sun and the fresh air made a
sweet resting place, grew a pretty little fir tree. The situation was
all that could be desired; and yet the tree was not happy, it wished so
much to be like its tall companions, the pines and firs which grew
around it.

The sun 


Documentation for the following code: https://www.geeksforgeeks.org/python-maketrans-translate-functions/

- How to use translate together with the helper function maketrans

In [10]:
#create function that can clean the text
def clean_doc(doc): #make a function called clean_doc
	# split into tokens by white space
	tokens = doc.split() #get a list with all words (tokens)
	# remove punctuation from each token
	table = str.maketrans('', '', string.punctuation) #third argument specifies the character we want to delete
	tokens = [w.translate(table) for w in tokens] #use translation mapping from table and loop through all words in token
	# remove remaining tokens that are not alphabetic
	tokens = [word for word in tokens if word.isalpha()] #isalpha() checks whether the string consists of alphabetic characters only. Replace word with word if it is alphabetical. 
	# make lower case
	tokens = [word.lower() for word in tokens] #replace word in lower case with word in token 
	return tokens

In [11]:
#use the cleaning function on the whole document
tokens = clean_doc(doc)
print(tokens[:20])
print('Total Tokens: %d' % len(tokens)) #print total number of tokens
print('Unique Tokens: %d' % len(set(tokens))) #group similar tokens and print the number



['away', 'in', 'the', 'forest', 'where', 'the', 'warm', 'sun', 'and', 'the', 'fresh', 'air', 'made', 'a', 'sweet', 'resting', 'place', 'grew', 'a', 'pretty']
Total Tokens: 39079
Unique Tokens: 3974


Now the text is cleaned and we need to divide into sequences.

We have to decide the length of the input sequences, which is the number of words that the model will train on. This is also the number of words which will be used as the seed text, when using the model to actually generate new sequences. 

In the tutorial 50 words are suggested. We will start with that and then in the fifth lesson we might try to only use sequences inside sentences, though this will minimize the amount of training data. 

In [12]:
# organize the text into sequences of tokens
length = 50 + 1 #define the length of the sequences, 1 is the output word
sequences = list() #create an empty list, where we will store all the sequences

for i in range(length, len(tokens)): #range([start], stop[, step])
	# select sequence of tokens
	seq = tokens[i-length:i] #make sequences with length of 50 + 1
	# convert into a line
	line = ' '.join(seq) #join the tokens into a line in the sequence
	# store
	sequences.append(line) #append all the lines to the empty list created before the loop
print('Total Sequences: %d' % len(sequences)) #print the total amount (length of sequence) of sequences 


print(sequences[2])

Total Sequences: 39028
the forest where the warm sun and the fresh air made a sweet resting place grew a pretty little fir tree the situation was all that could be desired and yet the tree was not happy it wished so much to be like its tall companions the pines and firs which


In [13]:
# save tokens to file, one dialog per line
def save_doc(lines, filename): #define function called save_doc() which takes two inputs
	data = '\n'.join(lines) #join lines, separate by line shift 
	file = open(filename, 'w')
	file.write(data)
	file.close()

In [14]:
# save sequences to file
out_filename = 'clean_text.txt'
save_doc(sequences, out_filename)#use the function on the sequences

# Lesson 3 - Train the generative model

Step by step:
 
- Load the cleaned data and divide it into training sequences
- Map each word to a unique integer i.e. word to vector representation
- Separate the input sequences into input and output elements



In [15]:
#load the cleaned data
doc = load_text('clean_text.txt')

#split the text according to line shift (every string is 51 words)
lines = doc.split('\n') #use split() function, \n is a regular expression for line shift

#check the type
type(lines)#its a list

list

Documentation for getting keras and tensorflow packages to work:

https://keras.io/getting-started/functional-api-guide/

https://www.tensorflow.org/install/source

In [25]:
#tokenizer = Tokenizer() #define function Tokenizer() as the variable tokenizer
#tokenizer.fit_on_texts(lines) #fit_on_text() tells it what data to train on. We train it on the entire training data, finds all of the unique words in the data and assigns each a unique integer, from 1 to the total number of words
#sequences = tokenizer.texts_to_sequences(lines) #convert each sequence from a list of words to a list of integers

print(sequences[:1]) #all sequences are represented by vectors, consisting of an integer corresponding to each word in the vector

tokenizer.word_index #check out the mapping of integers to words


[[93, 7, 1, 179, 67, 1, 246, 285, 2, 1, 332, 456, 103, 4, 676, 2093, 148, 261, 4, 270, 33, 260, 59, 1, 2092, 8, 28, 13, 48, 29, 1132, 2, 211, 1, 59, 8, 27, 302, 9, 491, 26, 104, 3, 29, 70, 140, 398, 1130, 1, 3973, 2]]


{'the': 1,
 'and': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'he': 6,
 'in': 7,
 'was': 8,
 'it': 9,
 'his': 10,
 'they': 11,
 'had': 12,
 'that': 13,
 'as': 14,
 'with': 15,
 'but': 16,
 'for': 17,
 'you': 18,
 'she': 19,
 'her': 20,
 'i': 21,
 'at': 22,
 'on': 23,
 'said': 24,
 'him': 25,
 'so': 26,
 'not': 27,
 'all': 28,
 'be': 29,
 'were': 30,
 'is': 31,
 'one': 32,
 'little': 33,
 'them': 34,
 'when': 35,
 'have': 36,
 'their': 37,
 'which': 38,
 'this': 39,
 'old': 40,
 'who': 41,
 'out': 42,
 'there': 43,
 'up': 44,
 'then': 45,
 'by': 46,
 'from': 47,
 'could': 48,
 'very': 49,
 'my': 50,
 'are': 51,
 'will': 52,
 'we': 53,
 'what': 54,
 'no': 55,
 'some': 56,
 'if': 57,
 'man': 58,
 'tree': 59,
 'into': 60,
 'would': 61,
 'do': 62,
 'came': 63,
 'been': 64,
 'now': 65,
 'me': 66,
 'where': 67,
 'time': 68,
 'about': 69,
 'like': 70,
 'an': 71,
 'did': 72,
 'down': 73,
 'how': 74,
 'see': 75,
 'before': 76,
 'only': 77,
 'son': 78,
 'over': 79,
 'two': 80,
 'young': 81,
 'beautiful': 8

In [26]:
#check vocabulary size
vocab_size = len(tokenizer.word_index) + 1 #+1 because indexing of arrays starts at zero, and the first word is assigned the integer of 1

vocab_size

3975

Now we have divided the cleaned text into training sequences and assigned each to work to an integer, so that all the sequences are represented by vectors of intergers. 

Next step is to divide it into input and output sequences. The outputs are the +1, which we have added to each sequences in lesson 2. 

In [27]:

# separate into input and output
sequences = array(sequences) #create an array with the sequences
#separate into input and output sequences
X, y = sequences[:,:-1], sequences[:,-1] #X is the whole sequences without the last integer, y is the last integer in the sequence
print(X) #input
print(y) #output
y = to_categorical(y, num_classes=vocab_size) #convert to one-hot encoding, represent by 1 and 0
print(y)
seq_length = X.shape[1] #set sequence length to the number of columns in X, so to 50 in this case

[[  93    7    1 ... 1130    1 3973]
 [   7    1  179 ...    1 3973    2]
 [   1  179   67 ... 3973    2 2094]
 ...
 [  52  290    4 ...   11   30   49]
 [ 290    4  792 ...   30   49   40]
 [   4  792  269 ...   49   40 3974]]
[   2 2094   38 ...   40 3974   46]
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


# Lesson 4.a - Fit and use the generative model


Step by step:
 
- Fit and save the model
- Load the data and the model
- Generate text


First we will create the model, by adding layers to it

In [28]:
model = Sequential() #define model, use sequential model function
model.add(Embedding(vocab_size, 50, input_length=seq_length)) #add embedding layer, 50 is the dimensions which will be used to represent each word vector
model.add(LSTM(100, return_sequences=True)) #add hidden layer, long short term memory layer
model.add(LSTM(100)) #100 is the number of units in our hidden layer
model.add(Dense(100, activation='relu')) #dense specifies the structure of the neural network, 100 refer to that there are 100 neurons in the first hidden layer, as defined above. Relu is an argument of rectified linear unit.  
model.add(Dense(vocab_size, activation='softmax')) #softmax transform to probabilities 
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 50, 50)            198750    
_________________________________________________________________
lstm_1 (LSTM)                (None, 50, 100)           60400     
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 3975)              401475    
Total params: 751,125
Trainable params: 751,125
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
#it's a multilevel predicter, because it's categorical, we want a measure which is accuracy, and a cost function which is optimized by adam
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) 

Now we are ready to train the model.

For the sake of showing how the model works I have just putted epochs=1. In the real model we ran it one 100 epochs. 

In [30]:
# fit model
model.fit(X, y, batch_size=128, epochs=1)

Epoch 1/1
39028/39028 [==============================] - 203s 5ms/step - loss: 6.4798 - acc: 0.0712


Training the model took a long time, between 20 and 40 hours. 

In [31]:
# save the model to file
model.save('model.h5')
# save the tokenizer
dump(tokenizer, open('tokenizer.pkl', 'wb')) #w stands for write

# Lesson 4.b - Fit and use the generative model

The model is ready for use. First we will try just to generate one word at a time. After this we will create a function which generates a specified number of words. 

In [33]:
#need the text, so we can use a sequence as a source input for generating the text
doc = load_text('clean_text.txt') #load cleaned sequences 

lines = doc.split('\n') #split by new line



In [34]:
#specify the sequence length
seq_length = len(lines[0].split()) - 1 #look at the first line, split sequences by words, count and minus 1

In [35]:
#load the model
model = load_model('model.h5')


# load the tokenizer
tokenizer = load(open('tokenizer.pkl', 'rb')) #r stands for read

In [56]:
#select a seed text
seed_text = lines[randint(0,len(lines))] #randint returns a random integer from 0 to the length of lines, index it
print(seed_text + '\n') #print the selected seed text and make a line shift

they had thought he would never come back to reproach them for their wickedness know what to paul said to them quietly shall never see me again off with he next took the three apples out of his pocket and placed them all in the prettiest places he could find after



In [57]:
#use tokenizer to assign an integer to every word in the seed text
encoded = tokenizer.texts_to_sequences([seed_text])[0]

#exclude the output word, so take the last 50 words
encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre') #pre indicates that it should take the values from the begining of the sequence


In [61]:
#the model.preict_classes will return the index of the word with the highest probability 

yhat = model.predict_classes(encoded, verbose=0) #verbose specifies how  you want to 'see' the training progress for each epoch



In [60]:
#look up in the tokenizer what word the indexed word corresponds to
out_word = '' #empty variable to store the word output word in 
for word, index in tokenizer.word_index.items(): #loop through the tokenizers
	if index == yhat: #if the index is equally to yhat, assign the word to the variable out_word
		out_word = word
		break



Lets create a function

In [49]:
#the input sequences will get too long, when adding the output word, need to make sure that it's always 50 words long
encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre') #pre indicates that it should take the values from the begining of the sequence

In [50]:
#create a function for generating new sequences 
#the function takes 5 inputs
def generate_seq(model, tokenizer, seq_length, seed_text, n_words): #n_words is the number of words to generate 
	result = list() #create and empty list
	in_text = seed_text #assign the see_text to a variable 
	# generate a fixed number of words
	for _ in range(n_words): #range(), first argument is the number of integers to generate, starting from zero
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0] #take the first sequence
		# truncate sequences to a fixed length
		encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre') #make sure that the sequence is 50 words
		# predict probabilities for each word
		yhat = model.predict_classes(encoded, verbose=0)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text += ' ' + out_word #add the output word to the sequence we are currently working with 
		result.append(out_word) #append the word to the empty list
	return ' '.join(result) #''.join creates a space between each word in the result list and makes a string

In [52]:

# generate new text, use the function on the model
generated = generate_seq(model, tokenizer, seq_length, seed_text, 50)
print(generated)


#save the generated text
out_filename = 'first_output1.txt'

save_doc(generated, out_filename)

the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the


As can be seen in appendix D, "Output from the simple model", the first output was better than the one above. This is due to the low amount of data in this example and because we only ran one epoch when training the model on the data. 

# Lesson 5.a - Improve Language Model


I have decided to create sequences which correspond to single sentences, instead of having sequences extending over different sentences. But for the model to work, all the sequences need to be the same length (e.g. some sentences have a length of 3 and others a length of 130). This means that we need to create padded sequences, where we add zeros in the beginning of each sequence, so all of them ends up being the same length.  


In [74]:
#load nltk library
nltk.download('punkt') #the library can use punctuation to divide the text into sentences

#define tokenizer, use pretrained from the corpus
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

#assign doc to data
data = doc

#use function sent_tokenize from the nltk package to divide the text into sentences
sentence_list = sent_tokenize(data)

#print the number of sentences
print(len(sentence_list))

#check the type, it's a list
type(sentence_list)

#index to see an example
sentence_list[5] #need to remove the punctuation and have in lower case




[nltk_data] Downloading package punkt to
[nltk_data]     /Users/signeklovekjaer/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
80842


'Originally they\ngave to their gods of their best.'

Now we need to clean the text and prepare the sequences as we did in lesson 2 and 3. We cannot use the exact same code, as the lines are now in unequal lengths. 

In [75]:
#check if cleaning function works on one sentence in the sentence list
print(clean_doc(sentence_list[3])) #it does

#make an empty list
sentence_clean_list = []

#make a loop which runs through the list of sentences and uses the clean_doc() function
for sentence in sentence_list:
    y = clean_doc(sentence) #save in y and append to empty list
    sentence_clean_list.append(y)
    

#print(sentence_clean_list[:10])

#check to see if the punctuation is removed and if it's in lower case
print(sentence_clean_list[5]) #it is

        

['that', 'portion', 'of', 'the', 'ancient', 'aryan', 'race', 'which', 'poured', 'from', 'the', 'central', 'plain', 'of', 'asia', 'through', 'the', 'rocky', 'defiles', 'of', 'what', 'we', 'now', 'call', 'the', 'frontier', 'to', 'populate', 'the', 'fertile', 'lowlands', 'of', 'india', 'had', 'gods', 'who', 'must', 'once', 'have', 'been', 'wholly', 'heroic', 'but', 'who', 'came', 'in', 'time', 'to', 'be', 'more', 'degraded', 'than', 'the', 'most', 'vicious', 'of', 'lustful', 'criminals']
['originally', 'they', 'gave', 'to', 'their', 'gods', 'of', 'their', 'best']


We need to check the length of the sentences, as we need to use this information then padding the sentences into sequences. 

In [76]:
#check the length of a random sentence
print(len(sentence_clean_list[3]))

length = []
for sentence in sentence_clean_list:
    l = len(sentence)
    length.append(l)

    
print(max(length))#print the maximum length of a sentence

print(min(length))#print the minimum length of a sentence


58
348
0


For some reasons, some of the sentences are on a length of zero. I will delete these. In relation to this, some of the sentences are really long. Because we will use padded sequences, all sequences will end up being the same length as the longest sentence. I will delete the few sentences which are longer than 130 words. 

In [77]:
#remove sentences less than 1 word long and longer than 130
sentence_new_list1 = [s for s in sentence_clean_list if len(s) >= 1] 
sentence_new_list = [s for s in sentence_new_list1 if len(s) <= 130]


length_new = []
for sentence in sentence_new_list:
    l = len(sentence)
    length_new.append(l)

    
print(max(length_new))

print(min(length_new))


#check how many sentences we have removed
print('Sentences removed after deleting sentences shorter than 1:', len(sentence_clean_list) - len(sentence_new_list1) )
print('Sentences removed after deleting sentences longer than :', len(sentence_new_list1) - len(sentence_new_list)) 



130
1
Sentences removed after deleting sentences shorter than 1: 393
Sentences removed after deleting sentences longer than : 97


In [78]:
# turn into (not separated) sentence, check method on number 5 in the list
line = ' '.join(sentence_new_list[5]) 

print(line) #it works

#create empty list
sequences_sent = []

#create a loop to do it at all the sentences
for sentence in sentence_new_list:
    line = ' '.join(sentence)
    sequences_sent.append(line)

print(sequences_sent[0])

originally they gave to their gods of their best
as a little child holds out its hands to catch the sunbeams to feel and to grasp what so its eyes tell it is actually there so down through the ages men have stretched out their hands in eager endeavour to know their god


Now the sentences are ready and we can continue as we did in lesson 2 and 3 with saving the sentences and assigning an integer to each word. 

In [79]:
# save the sentences to file, one dialog per line
def save_doc(lines, filename):
	data = '\n'.join(lines)
	file = open(filename, 'w')
	file.write(data)
	file.close()

In [81]:
# save sentences to file
out_filename = 'clean_text_sentences.txt'
save_doc(sequences_sent, out_filename)

In [82]:
#load the cleaned data with sentences
doc = load_text('clean_text_sentences.txt')

#split the text according to line shift
lines = doc.split('\n')

#check the type
type(lines)#its a list


print(lines[0])



as a little child holds out its hands to catch the sunbeams to feel and to grasp what so its eyes tell it is actually there so down through the ages men have stretched out their hands in eager endeavour to know their god


In [83]:
tokenizer = Tokenizer() #define function Tokenizer() as the variable tokenizer
tokenizer.fit_on_texts(lines) #fit_on_text() tells it what data to train on. We train it on the entire training data, finds all of the unique words in the data and assigns each a unique integer, from 1 to the total number of words
sequences_sent = tokenizer.texts_to_sequences(lines) #convert each sequence from a list of words to a list of integers

#print(sequences_sent[:100]) #all sequences are represented by vectors, consisting of an integer corresponding to each word in the vector

tokenizer.word_index #check out the mapping of integers to words

print(sequences_sent[0])

[18, 5, 49, 265, 4280, 36, 135, 262, 3, 860, 1, 4529, 3, 616, 2, 3, 4401, 51, 27, 135, 168, 156, 11, 31, 2426, 45, 27, 63, 145, 1, 4530, 210, 34, 832, 36, 50, 262, 8, 2387, 12099, 3, 125, 50, 639]


# Lesson 5.b - Improve Language Model


In the model all the input sequences need to be the same length. We therefore need to pad or truncate the different sentences. When you pad the sequences, you add zeros, so that they all become the same length (lenght of the longest sentence). In that case we will have to create an masking input layer which will ignore padded values. This means that padded inputs have no impact on learning. But we will start by padding all the sentences. 

In [84]:
#will padd zeros in front, pre is the default option
padded = pad_sequences(sequences_sent)
print(padded)


len(padded[3]) #all sequences are now 130 long



[[    0     0     0 ...   125    50   639]
 [    0     0     0 ...     4    50 14117]
 [    0     0     0 ...     1   214   347]
 ...
 [    0     0     0 ...     2  1308    82]
 [    0     0     0 ...     1   633   863]
 [    0     0     0 ...     4    13   242]]


130

In [85]:
#check vocabulary size
vocab_size = len(tokenizer.word_index) + 1 #+1 because indexing of arrays starts at zero, and the first word is assigned the integer of 1

vocab_size

28730

In [86]:
# separate into input and output
sequences_sent = array(padded) #create an array with the sequences

X, y = sequences_sent[:,:-1], sequences_sent[:,-1] #separate into input and output sequences
print(X) #input
print(y) #output
y = to_categorical(y, num_classes=vocab_size) #convert to one-hot encoding
print(y)
seq_length_sent = X.shape[1] #set sequence length to the number of columns in X

len(X[1])
len(y)

print(y[[3]])

print(max(y[3])) #check if there is one-hot encoding for the output word

print(min(y[3]))

print(len(X[1]))

[[   0    0    0 ...    3  125   50]
 [   0    0    0 ... 4402    4   50]
 [   0    0    0 ...  188    1  214]
 ...
 [   0    0    0 ... 1260    2 1308]
 [   0    0    0 ...   19    1  633]
 [   0    0    0 ...  255    4   13]]
[  639 14117   347 ...    82   863   242]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]]
1.0
0.0
129


Now we are ready to create the model. One difference to the first model, is that we need to add a masking layer, which specify that the model should not take zeros into account (what we have padded the sequences with). Another difference is that the input sequences now is 130 words long instead of 50 as in the first model.  

In [87]:
#create the model
model = Sequential() #define model, use sequential model function
model.add(Masking(mask_value=0, input_shape=(seq_length_sent,))) #the masking layer, which is needed because of the padded sequences
model.add(Embedding(vocab_size, 50, input_length=seq_length_sent)) #add embedding layer, 50 is the dimensions which will be used to represent each word vector
model.add(LSTM(100, return_sequences=True)) #add hidden layer, long short term memory layer
model.add(LSTM(100))
model.add(Dense(100, activation='relu')) #dense specifies the structure of the neural network, 100 refer to that there are 100 neurons in the first hidden layer, as defined above. Relu is an argument of rectified linear unit.  
model.add(Dense(vocab_size, activation='softmax')) #softmax transform to probabilities 
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
masking_1 (Masking)          (None, 129)               0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 129, 50)           1436500   
_________________________________________________________________
lstm_1 (LSTM)                (None, 129, 100)          60400     
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 28730)             2901730   
Total params: 4,489,130
Trainable params: 4,489,130
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) #it's a multilevel predicter, because it's categorical, we want a measure which is accuracy, and a cost function which is optimized by adam
# fit model
model.fit(X, y, batch_size=128, epochs=100)

Epoch 1/100
 1664/80352 [..............................] - ETA: 24:05 - loss: 10.2595 - acc: 0.0186

Due to processing power on my computer, the outputs for the next steps are not visible in this Jupyter notebook. We ran the model on another computer. But the steps are exactly the same as for the simple model under Lesson 4. 

In [ ]:
# save the model to file
model.save('model.h5_sentence')
# save the tokenizer
dump(tokenizer, open('tokenizer.pkl_sentence', 'wb')) #w stands for write

In [ ]:
#need the text, so we can use a sequence as a source input for generating the text
doc = load_text('Data/clean_text_sentences.txt') #load cleaned sequences 

lines = doc.split('\n') #split by new line


lines[5]

In [ ]:
#specify the sequence length
seq_length_sent = X.shape[1]

print(seq_length_sent)

In [ ]:
#load the model
model = load_model('model.h5_sentence')


# load the tokenizer
tokenizer = load(open('tokenizer.pkl_sentence', 'rb')) #r stands for read

In [ ]:
#select a seed text
seed_text_sentence = lines[randint(0,len(lines))] #randint returns a random integer from 0 to the length of lines, index it
print(seed_text_sentence + '\n') #print the selected seed text and make a line shift

In [ ]:
#the input sequences will get too long, when adding the output word, need to make sure that it's always 129 words long
#encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre') #pre indicates that it should take the values from the begining of the sequence

In [ ]:
#create a function for generating new sequences 
def generate_seq(model, tokenizer, seq_length_sent, seed_text_sentence, n_words): #n_words is the number of words to generate 
	result = list() #create and empty list
	in_text = seed_text_sentence #assign the see_text to a variable 
	# generate a fixed number of words
	for _ in range(n_words): #range(), first argument is the number of integers to generate, starting from zero
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0] #take the first sequence
		# truncate sequences to a fixed length
		encoded = pad_sequences([encoded], maxlen=seq_length_sent, truncating='pre') #make sure that the sequence is 50 words
		# predict probabilities for each word
		yhat = model.predict_classes(encoded, verbose=0)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text += ' ' + out_word #add the output word to the sequence we are currently working with 
		result.append(out_word) #append the word to the empty list
	return ' '.join(result) #''.join creates a space between each word in the result list and makes a string

In [ ]:

# generate new text
generated = generate_seq(model, tokenizer, seq_length_sent, seed_text_sentence, 20)
print(generated)


#save the generated text

out_filename = 'Data/first_output_sentence.txt'

save_doc(generated, out_filename)

The text generated from this model can be seen in appendix D "Output from model using natural sentences as training sequences". 